ARG FROM_IMAGE=zyclonite/zerotier
ARG FROM_VERSION=latest

FROM ${FROM_IMAGE}:${FROM_VERSION}

RUN apk add --no-cache --purge --clean-protected iptables \
  && rm -rf /var/cache/apk/*

ENV LOG_PATH=/var/log/supervisor

COPY scripts/entrypoint-bridge.sh /usr/sbin/

EXPOSE 9993/udp

ENTRYPOINT ["entrypoint-bridge.sh"]

CMD ["-U"]
